apiVersion: v1
kind: Pod
metadata:
  name: springapp
  namespace: test-ns
  labels:
    app: springapp
spec:
  containers:
  - name: springapp
    image: udaydk/spring:1
    ports:
    - containerPort: 5000
    resources:
      requests:
        cpu: 1
        memory: 512Mi
      limits: 
        cpu: 1
        memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: springappsv
  namespace: test-ns
spec:
  type: LoadBalancer
  selector:
    app: springapp
  ports:
  - port: 80
    targetPort: 5000

